# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# set workdir
WORKDIR /app

# copy project files
COPY pyproject.toml .
COPY main.py .
COPY uv.lock .
COPY README.md .

# install dependencies
RUN pip install --no-cache-dir .

# expose any needed ports (none for stdio)

# default command
CMD ["mcp-akshare"]
